version: '2'

# compose setup for test purposes

services:
  mongodb:
    build: ./3.2/
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGODB_USER: admin
      MONGODB_DATABASE: admin
      MONGODB_PASS: secret

  mongo-express:
    image: mongo-express
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
